version: '3.8'

services:
  web:
    build: .
    command: gunicorn django_bootstrap.wsgi:application --bind 0.0.0.0:8000 --reload --workers 3
    volumes:
      - ./:/usr/src/app/
#    ports:
#      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - 5555:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: